name: AI Review Î±

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.py'
      - 'astrology-bot/*py'
      - '!*.md'

jobs:
  request_ai_review:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: POST Dify API
        env:
          API_URL: "https://api.dify.ai/v1/workflows/run"
          API_KEY: ${{ secrets.DIFY_KEY }}
        run: |
          response=$(curl -s -X POST "$API_URL" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "inputs": { "url": "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" },
              "response_mode": "blocking",
              "user": "xxxxxx"
            }')

          echo "Response: $response"
